#!/bin/bash

###############################################################################
# datacenter_log_manager.sh
#
# GUI-driven log management and infrastructure monitoring tool for data centers.
# Provides a Zenity-based interface to eliminate manual command errors and
# reduce the learning curve for operators across multiple shifts.
#
# Features:
#   - Collect and compress logs from remote nodes via SSH
#   - Upload log bundles to a central FTP server
#   - Verify and restart critical services
#   - Check node connectivity across a server group
#   - Gather basic node hardware information
#   - Manage serial numbers and asset tags
#
# Requirements:
#   - Linux with X display (GNOME or compatible desktop)
#   - zenity, curl, tar, ssh, ping, systemctl
#   - Config file: ~/.config/dclogmanager/settings.conf
#
# Usage:
#   chmod +x datacenter_log_manager.sh
#   ./datacenter_log_manager.sh
###############################################################################

set -euo pipefail


###############################################################################
# CONFIGURATION — loaded from external file, never hardcoded
###############################################################################

CONFIG_DIR="$HOME/.config/dclogmanager"
CONFIG_FILE="$CONFIG_DIR/settings.conf"
LOG_STAGING_DIR="$HOME/Desktop/Logs"
TEMP_DIR="/tmp/dclogmanager"

# Defaults — overridden by config file
FTP_HOST=""
FTP_USER=""
FTP_PASS=""
FTP_REMOTE_PATH="/logs"
SSH_USER="admin"
NODE_PREFIX="node"
NODE_START=1
NODE_END=10
SERVICES="ssh,cron,rsyslog"
HELP_URL="https://github.com/your-username/datacenter-log-manager"
APP_TITLE="DataCenter Log Manager"

load_config() {
    if [ ! -f "$CONFIG_FILE" ]; then
        zenity --error \
            --title="$APP_TITLE — Configuration Error" \
            --text="Config file not found:\n$CONFIG_FILE\n\nRun the setup wizard first (Help → Setup Wizard)."
        return 1
    fi
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"

    for var in FTP_HOST FTP_USER FTP_PASS; do
        if [ -z "${!var:-}" ]; then
            zenity --error \
                --title="$APP_TITLE — Configuration Error" \
                --text="Missing required variable '$var' in:\n$CONFIG_FILE"
            return 1
        fi
    done
    return 0
}


###############################################################################
# SETUP WIZARD — creates the config file interactively on first run
###############################################################################

run_setup_wizard() {
    zenity --info \
        --title="$APP_TITLE — Setup Wizard" \
        --text="Welcome! Let's configure your environment.\n\nYou will need:\n• FTP server address and credentials\n• SSH username for remote nodes\n• Node naming convention (e.g. 'node' for node1, node2...)"

    local ftp_host ftp_user ftp_pass ftp_path ssh_user \
          node_prefix node_start node_end services_input

    ftp_host=$(zenity --entry \
        --title="Setup — FTP Server" \
        --text="FTP server hostname or IP:") || return 1

    ftp_user=$(zenity --entry \
        --title="Setup — FTP Credentials" \
        --text="FTP username:") || return 1

    ftp_pass=$(zenity --password \
        --title="Setup — FTP Credentials") || return 1

    ftp_path=$(zenity --entry \
        --title="Setup — FTP Remote Path" \
        --text="Remote path for log uploads:" \
        --entry-text="/logs") || return 1

    ssh_user=$(zenity --entry \
        --title="Setup — SSH User" \
        --text="SSH username for remote nodes:" \
        --entry-text="admin") || return 1

    node_prefix=$(zenity --entry \
        --title="Setup — Node Naming" \
        --text="Node name prefix (e.g. 'node' gives node1, node2...):" \
        --entry-text="node") || return 1

    node_start=$(zenity --entry \
        --title="Setup — Node Range" \
        --text="First node number:" \
        --entry-text="1") || return 1

    node_end=$(zenity --entry \
        --title="Setup — Node Range" \
        --text="Last node number:" \
        --entry-text="10") || return 1

    services_input=$(zenity --entry \
        --title="Setup — Services to Monitor" \
        --text="Services to monitor (comma-separated):" \
        --entry-text="ssh,cron,rsyslog") || return 1

    mkdir -p "$CONFIG_DIR"
    chmod 700 "$CONFIG_DIR"

    cat > "$CONFIG_FILE" << EOF
# DataCenter Log Manager — Configuration
# Generated by setup wizard on $(date)
# Keep this file private — contains credentials

FTP_HOST=$ftp_host
FTP_USER=$ftp_user
FTP_PASS=$ftp_pass
FTP_REMOTE_PATH=$ftp_path
SSH_USER=$ssh_user
NODE_PREFIX=$node_prefix
NODE_START=$node_start
NODE_END=$node_end
SERVICES=$services_input
HELP_URL=https://github.com/your-username/datacenter-log-manager
EOF
    chmod 600 "$CONFIG_FILE"

    zenity --info \
        --title="$APP_TITLE — Setup Complete" \
        --text="Configuration saved to:\n$CONFIG_FILE\n\nYou can edit it at any time."
}


###############################################################################
# VALIDATION HELPERS
###############################################################################

# Validates that a ticket/job ID is non-empty and alphanumeric
# Usage: validate_ticket_id <id>  → 0=valid, 1=invalid
validate_ticket_id() {
    local id="$1"
    if [ -z "$id" ]; then
        zenity --error --title="$APP_TITLE" \
            --text="Ticket / Job ID cannot be empty."
        return 1
    fi
    if ! [[ "$id" =~ ^[A-Za-z0-9_-]+$ ]]; then
        zenity --error --title="$APP_TITLE" \
            --text="Ticket / Job ID contains invalid characters.\nUse only letters, numbers, hyphens, and underscores."
        return 1
    fi
    return 0
}

# Validates that a node name matches the configured prefix + number
# Usage: validate_node_name <name>  → 0=valid, 1=invalid
validate_node_name() {
    local name="$1"
    if [[ "$name" =~ ^${NODE_PREFIX}[0-9]+$ ]]; then
        return 0
    fi
    zenity --error --title="$APP_TITLE" \
        --text="Invalid node name: '$name'\nExpected format: ${NODE_PREFIX}1, ${NODE_PREFIX}2, ..."
    return 1
}

# Validates that an IP address is well-formed and each octet is 0-255
# Usage: validate_ip <ip>  → 0=valid, 1=invalid
validate_ip() {
    local ip="$1"
    local pattern='^([0-9]{1,3}\.){3}[0-9]{1,3}$'

    if [[ "$ip" =~ $pattern ]]; then
        # Verify each octet is within valid range (0-255)
        local IFS='.'
        read -ra octets <<< "$ip"
        for octet in "${octets[@]}"; do
            if [ "$octet" -gt 255 ]; then
                zenity --error --title="$APP_TITLE" \
                    --text="Invalid IP address: octet '$octet' is out of range (0-255)"
                return 1
            fi
        done
        return 0
    fi
    zenity --error --title="$APP_TITLE" \
        --text="Invalid IP address format: '$ip'"
    return 1
}


###############################################################################
# CONNECTIVITY
###############################################################################

# Pings a single node
ping_node() {
    local target
    target=$(zenity --entry \
        --title="$APP_TITLE — Ping" \
        --text="Enter node name or IP to ping:" \
        --entry-text="${NODE_PREFIX}1") || return

    gnome-terminal -- bash -c "ping -c 20 $target; echo; echo 'Press Enter to close'; read" &
}

# Pings all nodes in the configured range and shows a summary
check_all_nodes() {
    local results_file
    results_file=$(mktemp)
    local reachable=0
    local unreachable=0

    (
        local total=$(( NODE_END - NODE_START + 1 ))
        local current=0

        for i in $(seq "$NODE_START" "$NODE_END"); do
            local node="${NODE_PREFIX}${i}"
            current=$(( current + 1 ))
            echo "$(( current * 100 / total ))"
            echo "# Checking $node..."

            if ping -c 1 -W 2 "$node" &>/dev/null; then
                echo "✔  $node — reachable" >> "$results_file"
                reachable=$(( reachable + 1 ))
            else
                echo "✘  $node — UNREACHABLE" >> "$results_file"
                unreachable=$(( unreachable + 1 ))
            fi
        done

        echo "100"
        echo "# Done"
    ) | zenity --progress \
        --title="$APP_TITLE — Checking Nodes" \
        --text="Starting connectivity check..." \
        --percentage=0 --auto-close --auto-kill

    {
        echo "=== Connectivity Report — $(date) ==="
        echo "Reachable: $reachable  |  Unreachable: $unreachable"
        echo "---"
        cat "$results_file"
    } > "${results_file}.report"

    zenity --text-info \
        --title="$APP_TITLE — Connectivity Report" \
        --width=500 --height=400 \
        --filename="${results_file}.report"

    rm -f "$results_file" "${results_file}.report"
}


###############################################################################
# SERVICE MANAGEMENT
###############################################################################

# Checks each configured service and starts it if stopped
verify_and_start_services() {
    local report_file
    report_file=$(mktemp)

    echo "=== Service Status Report — $(date) ===" >> "$report_file"

    IFS=',' read -ra service_list <<< "$SERVICES"
    for svc in "${service_list[@]}"; do
        svc=$(echo "$svc" | tr -d ' ')
        if systemctl is-active --quiet "$svc" 2>/dev/null; then
            echo "✔  $svc — running" >> "$report_file"
        else
            echo "⚠  $svc — stopped. Attempting to start..." >> "$report_file"
            if systemctl start "$svc" 2>/dev/null; then
                sleep 2
                echo "   → $svc started successfully" >> "$report_file"
            else
                echo "   → Failed to start $svc" >> "$report_file"
            fi
        fi
    done

    zenity --text-info \
        --title="$APP_TITLE — Service Status" \
        --width=450 --height=300 \
        --filename="$report_file"

    rm -f "$report_file"
}

# Restarts a single user-selected service
restart_single_service() {
    IFS=',' read -ra service_list <<< "$SERVICES"
    local zenity_args=()
    local first=TRUE

    for svc in "${service_list[@]}"; do
        svc=$(echo "$svc" | tr -d ' ')
        zenity_args+=("$first" "$svc")
        first=FALSE
    done

    local selected
    selected=$(zenity --list \
        --title="$APP_TITLE — Restart Service" \
        --text="Select a service to restart:" \
        --radiolist \
        --column="" --column="Service" \
        "${zenity_args[@]}") || return

    if systemctl restart "$selected" 2>/dev/null | \
        zenity --progress \
            --title="$APP_TITLE" \
            --text="Restarting $selected..." \
            --pulsate --auto-close --auto-kill; then
        zenity --info --title="$APP_TITLE" \
            --text="Service '$selected' restarted successfully."
    else
        zenity --error --title="$APP_TITLE" \
            --text="Failed to restart '$selected'."
    fi
}


###############################################################################
# LOG COLLECTION
###############################################################################

# Collects logs from a remote node via SSH, compresses them locally
# Usage: collect_node_logs <node_name> <ticket_id> <log_paths>
collect_node_logs() {
    local node="$1"
    local ticket_id="$2"
    local log_paths="$3"
    local staging_dir="$LOG_STAGING_DIR/ticket_${ticket_id}"
    local archive_name="${node}_$(date +%Y%m%d_%H%M%S).tar.gz"

    mkdir -p "$staging_dir"

    # Collect logs from node via SSH
    ssh -o ConnectTimeout=10 -o BatchMode=yes \
        "${SSH_USER}@${node}" \
        "tar -czf - $log_paths 2>/dev/null" \
        > "$staging_dir/$archive_name" 2>/dev/null

    if [ $? -eq 0 ] && [ -s "$staging_dir/$archive_name" ]; then
        echo "$staging_dir/$archive_name"
        return 0
    else
        rm -f "$staging_dir/$archive_name"
        return 1
    fi
}

# Interactive: collect logs from a single node
collect_single_node_logs_menu() {
    local node
    node=$(zenity --entry \
        --title="$APP_TITLE — Collect Logs" \
        --text="Node name or IP:" \
        --entry-text="${NODE_PREFIX}1") || return

    local ticket_id
    ticket_id=$(zenity --entry \
        --title="$APP_TITLE — Collect Logs" \
        --text="Ticket / Job ID:") || return

    validate_ticket_id "$ticket_id" || return

    local log_paths
    log_paths=$(zenity --entry \
        --title="$APP_TITLE — Collect Logs" \
        --text="Log paths to collect (space-separated):" \
        --entry-text="/var/log/syslog /var/log/messages") || return

    (
        echo "10"; echo "# Connecting to $node..."
        sleep 1
        echo "40"; echo "# Collecting logs from $node..."
        collect_node_logs "$node" "$ticket_id" "$log_paths"
        local status=$?
        echo "100"; echo "# Done"
        exit $status
    ) | zenity --progress \
        --title="$APP_TITLE — Collecting Logs" \
        --text="Starting..." \
        --percentage=0 --auto-close --auto-kill

    if [ $? -eq 0 ]; then
        zenity --info --title="$APP_TITLE" \
            --text="Logs collected successfully.\nStaged at:\n$LOG_STAGING_DIR/ticket_${ticket_id}/"
    else
        zenity --error --title="$APP_TITLE" \
            --text="Failed to collect logs from $node.\nCheck SSH connectivity and permissions."
    fi
}

# Collect logs from ALL nodes in the configured range
collect_all_nodes_logs_menu() {
    local ticket_id
    ticket_id=$(zenity --entry \
        --title="$APP_TITLE — Collect All Nodes" \
        --text="Ticket / Job ID:") || return

    validate_ticket_id "$ticket_id" || return

    local log_paths
    log_paths=$(zenity --entry \
        --title="$APP_TITLE — Collect All Nodes" \
        --text="Log paths to collect (space-separated):" \
        --entry-text="/var/log/syslog /var/log/messages") || return

    local success=0
    local failed=0
    local failed_nodes=""
    local total=$(( NODE_END - NODE_START + 1 ))
    local current=0

    (
        for i in $(seq "$NODE_START" "$NODE_END"); do
            local node="${NODE_PREFIX}${i}"
            current=$(( current + 1 ))
            echo "$(( current * 100 / total ))"
            echo "# Collecting logs from $node..."

            if collect_node_logs "$node" "$ticket_id" "$log_paths" &>/dev/null; then
                success=$(( success + 1 ))
            else
                failed=$(( failed + 1 ))
                failed_nodes="$failed_nodes\n  ✘ $node"
            fi
        done
        echo "100"
        echo "# Collection complete"
    ) | zenity --progress \
        --title="$APP_TITLE — Collecting All Node Logs" \
        --text="Starting..." \
        --percentage=0 --auto-close --auto-kill

    local summary="Collection complete for ticket: $ticket_id\n\n"
    summary+="✔  Successful: $success nodes\n"
    summary+="✘  Failed:     $failed nodes"
    [ -n "$failed_nodes" ] && summary+="\n$failed_nodes"

    zenity --info --title="$APP_TITLE — Collection Summary" --text="$summary"
}


###############################################################################
# FTP UPLOAD
###############################################################################

# Uploads a local archive to the FTP server
# Usage: upload_to_ftp <local_file> <remote_subdir>
upload_to_ftp() {
    local local_file="$1"
    local remote_subdir="$2"
    local filename
    filename=$(basename "$local_file")

    curl --silent --show-error \
        -u "${FTP_USER}:${FTP_PASS}" \
        -T "$local_file" \
        --ftp-create-dirs \
        "ftp://${FTP_HOST}${FTP_REMOTE_PATH}/${remote_subdir}/${filename}"

    return $?
}

# Interactive: upload staged logs for a ticket
upload_ticket_logs_menu() {
    local ticket_id
    ticket_id=$(zenity --entry \
        --title="$APP_TITLE — Upload Logs" \
        --text="Ticket / Job ID to upload:") || return

    validate_ticket_id "$ticket_id" || return

    local staging_dir="$LOG_STAGING_DIR/ticket_${ticket_id}"

    if [ ! -d "$staging_dir" ]; then
        zenity --error --title="$APP_TITLE" \
            --text="No staged logs found for ticket: $ticket_id\n\nCollect logs first."
        return 1
    fi

    local archives
    archives=$(find "$staging_dir" -name "*.tar.gz" | wc -l)

    if [ "$archives" -eq 0 ]; then
        zenity --error --title="$APP_TITLE" \
            --text="No log archives found in:\n$staging_dir"
        return 1
    fi

    zenity --question \
        --title="$APP_TITLE — Confirm Upload" \
        --text="Upload $archives archive(s) for ticket $ticket_id?\n\nDestination: ftp://$FTP_HOST$FTP_REMOTE_PATH/ticket_$ticket_id/" \
        --ok-label="Upload" --cancel-label="Cancel" || return

    local success=0
    local failed=0
    local total="$archives"
    local current=0

    (
        while IFS= read -r archive; do
            current=$(( current + 1 ))
            local fname
            fname=$(basename "$archive")
            echo "$(( current * 100 / total ))"
            echo "# Uploading $fname..."

            if upload_to_ftp "$archive" "ticket_${ticket_id}"; then
                success=$(( success + 1 ))
            else
                failed=$(( failed + 1 ))
            fi
        done < <(find "$staging_dir" -name "*.tar.gz")

        echo "100"
        echo "# Upload complete"
    ) | zenity --progress \
        --title="$APP_TITLE — Uploading to FTP" \
        --text="Connecting to $FTP_HOST..." \
        --percentage=0 --auto-close --auto-kill

    zenity --info --title="$APP_TITLE — Upload Summary" \
        --text="Upload complete for ticket: $ticket_id\n\n✔  Uploaded: $success files\n✘  Failed:   $failed files\n\nFTP path: ftp://$FTP_HOST$FTP_REMOTE_PATH/ticket_$ticket_id/"
}

# One-shot: collect logs from all nodes AND upload in sequence
collect_and_upload_all() {
    local ticket_id
    ticket_id=$(zenity --entry \
        --title="$APP_TITLE — Collect & Upload" \
        --text="Ticket / Job ID:") || return

    validate_ticket_id "$ticket_id" || return

    local log_paths
    log_paths=$(zenity --entry \
        --title="$APP_TITLE — Collect & Upload" \
        --text="Log paths to collect (space-separated):" \
        --entry-text="/var/log/syslog /var/log/messages") || return

    zenity --question \
        --title="$APP_TITLE — Confirm" \
        --text="This will:\n1. Collect logs from nodes ${NODE_PREFIX}${NODE_START} to ${NODE_PREFIX}${NODE_END}\n2. Upload all archives to:\n   ftp://$FTP_HOST$FTP_REMOTE_PATH/ticket_$ticket_id/\n\nProceed?" \
        --ok-label="Start" --cancel-label="Cancel" || return

    local success=0 failed=0 failed_nodes=""
    local total=$(( NODE_END - NODE_START + 1 ))
    local current=0

    (
        for i in $(seq "$NODE_START" "$NODE_END"); do
            local node="${NODE_PREFIX}${i}"
            current=$(( current + 1 ))
            echo "$(( current * 100 / total ))"
            echo "# [$current/$total] Collecting: $node..."

            local archive
            archive=$(collect_node_logs "$node" "$ticket_id" "$log_paths" 2>/dev/null)

            if [ $? -eq 0 ] && [ -f "$archive" ]; then
                echo "# [$current/$total] Uploading: $node..."
                if upload_to_ftp "$archive" "ticket_${ticket_id}"; then
                    success=$(( success + 1 ))
                else
                    failed=$(( failed + 1 ))
                    failed_nodes="$failed_nodes\n  upload failed: $node"
                fi
            else
                failed=$(( failed + 1 ))
                failed_nodes="$failed_nodes\n  unreachable: $node"
            fi
        done
        echo "100"; echo "# All done"
    ) | zenity --progress \
        --title="$APP_TITLE — Collect & Upload" \
        --text="Starting..." \
        --percentage=0 --auto-close --auto-kill

    local summary="Ticket: $ticket_id\n\n✔  Completed: $success nodes\n✘  Failed:    $failed nodes"
    [ -n "$failed_nodes" ] && summary+="\n$failed_nodes"
    summary+="\n\nFTP: ftp://$FTP_HOST$FTP_REMOTE_PATH/ticket_$ticket_id/"

    zenity --info --title="$APP_TITLE — Summary" --text="$summary"
}


###############################################################################
# NODE INFORMATION
###############################################################################

# Shows hardware/OS info for a single node via SSH
show_node_info() {
    local node
    node=$(zenity --entry \
        --title="$APP_TITLE — Node Info" \
        --text="Node name or IP:" \
        --entry-text="${NODE_PREFIX}1") || return

    local info_file
    info_file=$(mktemp)

    (
        echo "20"; echo "# Connecting to $node..."
        {
            echo "=== Node: $node — $(date) ==="
            echo ""
            ssh -o ConnectTimeout=10 -o BatchMode=yes \
                "${SSH_USER}@${node}" \
                "echo '--- Hostname ---'; hostname -f; \
                 echo '--- Uptime ---'; uptime; \
                 echo '--- OS ---'; cat /etc/os-release 2>/dev/null | head -3; \
                 echo '--- CPU ---'; lscpu | grep 'Model name\|CPU(s)\|Thread'; \
                 echo '--- Memory ---'; free -h; \
                 echo '--- Disk ---'; df -h / 2>/dev/null; \
                 echo '--- Network ---'; ip -br addr 2>/dev/null || ifconfig 2>/dev/null" 2>&1
        } >> "$info_file"
        echo "100"; echo "# Done"
    ) | zenity --progress \
        --title="$APP_TITLE" \
        --text="Gathering info from $node..." \
        --percentage=0 --auto-close --auto-kill

    zenity --text-info \
        --title="$APP_TITLE — $node Information" \
        --width=600 --height=500 \
        --filename="$info_file"

    rm -f "$info_file"
}

# Scans all nodes and reports basic reachability + hostname
scan_all_nodes_info() {
    local report_file
    report_file=$(mktemp)
    local total=$(( NODE_END - NODE_START + 1 ))
    local current=0

    (
        echo "=== Node Scan Report — $(date) ===" >> "$report_file"
        echo "" >> "$report_file"

        for i in $(seq "$NODE_START" "$NODE_END"); do
            local node="${NODE_PREFIX}${i}"
            current=$(( current + 1 ))
            echo "$(( current * 100 / total ))"
            echo "# Scanning $node..."

            if ping -c 1 -W 2 "$node" &>/dev/null; then
                local hostname uptime_info
                hostname=$(ssh -o ConnectTimeout=5 -o BatchMode=yes \
                    "${SSH_USER}@${node}" "hostname -f" 2>/dev/null || echo "SSH unavailable")
                uptime_info=$(ssh -o ConnectTimeout=5 -o BatchMode=yes \
                    "${SSH_USER}@${node}" "uptime -p" 2>/dev/null || echo "N/A")
                echo "✔  $node | $hostname | $uptime_info" >> "$report_file"
            else
                echo "✘  $node | UNREACHABLE" >> "$report_file"
            fi
        done
        echo "100"; echo "# Scan complete"
    ) | zenity --progress \
        --title="$APP_TITLE — Scanning Nodes" \
        --text="Starting scan..." \
        --percentage=0 --auto-close --auto-kill

    zenity --text-info \
        --title="$APP_TITLE — Node Scan Report" \
        --width=650 --height=450 \
        --filename="$report_file"

    rm -f "$report_file"
}


###############################################################################
# TAIL LOG (live view)
###############################################################################

tail_log() {
    local log_path
    log_path=$(zenity --entry \
        --title="$APP_TITLE — Tail Log" \
        --text="Log file to tail:" \
        --entry-text="/var/log/syslog") || return

    gnome-terminal -- bash -c "tail -f $log_path; echo; echo 'Press Enter to close'; read" &
}


###############################################################################
# MENUS
###############################################################################

menu_logs() {
    while option=$(zenity \
        --title "$APP_TITLE — Log Management" \
        --height=560 --width=400 \
        --list --text="Select an action:" \
        --column="" --column="Option" --radiolist \
        TRUE  "Collect logs from single node" \
        FALSE "Collect logs from all nodes" \
        FALSE "Upload staged logs to FTP" \
        FALSE "Collect & Upload all nodes" \
        FALSE "Tail a log file"); do

        case "$option" in
            "Collect logs from single node") collect_single_node_logs_menu ;;
            "Collect logs from all nodes")   collect_all_nodes_logs_menu ;;
            "Upload staged logs to FTP")     upload_ticket_logs_menu ;;
            "Collect & Upload all nodes")    collect_and_upload_all ;;
            "Tail a log file")               tail_log ;;
            *) exit ;;
        esac
    done
}

menu_nodes() {
    while option=$(zenity \
        --title "$APP_TITLE — Node Management" \
        --height=440 --width=280 \
        --list --text="Select an action:" \
        --column="" --column="Option" --radiolist \
        TRUE  "Ping a node" \
        FALSE "Check all nodes connectivity" \
        FALSE "Show node hardware info" \
        FALSE "Scan all nodes info"); do

        case "$option" in
            "Ping a node")                  ping_node ;;
            "Check all nodes connectivity") check_all_nodes ;;
            "Show node hardware info")      show_node_info ;;
            "Scan all nodes info")          scan_all_nodes_info ;;
            *) exit ;;
        esac
    done
}

menu_services() {
    while option=$(zenity \
        --title "$APP_TITLE — Service Management" \
        --height=200 --width=350 \
        --list --text="Select an action:" \
        --column="" --column="Option" --radiolist \
        TRUE  "Verify and start all services" \
        FALSE "Restart a single service"); do

        case "$option" in
            "Verify and start all services") verify_and_start_services ;;
            "Restart a single service")      restart_single_service ;;
            *) exit ;;
        esac
    done
}


###############################################################################
# MAIN — bootstrap and main menu loop
###############################################################################

# Create temp dir
mkdir -p "$TEMP_DIR" "$LOG_STAGING_DIR"

# First-run detection
if [ ! -f "$CONFIG_FILE" ]; then
    zenity --question \
        --title="$APP_TITLE — First Run" \
        --text="No configuration found.\n\nRun the setup wizard now?" \
        --ok-label="Run Wizard" --cancel-label="Exit" || exit 0
    run_setup_wizard || exit 1
fi

# Load config
load_config || exit 1

# Main menu loop
while option=$(zenity \
    --title "$APP_TITLE" \
    --height=560 --width=400 \
    --list --text="Welcome — what would you like to do?" \
    --column="" --column="Menu" --radiolist \
    TRUE  "📦  Log Management" \
    FALSE "🖥️  Node Management" \
    FALSE "⚙️  Service Management" \
    FALSE "🔧  Setup / Reconfigure" \
    FALSE "❓  Help"); do

    case "$option" in
        "📦  Log Management")     menu_logs ;;
        "🖥️  Node Management")    menu_nodes ;;
        "⚙️  Service Management") menu_services ;;
        "🔧  Setup / Reconfigure") run_setup_wizard ;;
        "❓  Help")               xdg-open "$HELP_URL" & ;;
        *) exit ;;
    esac
done
